### ISSUE TITLE
why debuginfo both have buildid and hash of file?

### ISSUE THREAD

**Issue by zdyj3170101136** [parca-dev/parca-agent#1105]
i find in debuginfo, use the buildid and hash of file to query parca
whether this file exist.

why should we compute the hash of file when  we already have buildid to uniquely identify a file?
```
func (di *Manager) exists(ctx context.Context, buildID, src string) bool {
	logger := log.With(di.logger, "buildid", buildID, "path", src)
	if _, ok := di.existsCache.GetIfPresent(buildID); ok {
		return true
	}

	// Hash of the source file.
	h, err := hash.File(src)
	if err != nil {
		level.Debug(logger).Log("msg", "failed to hash file", "err", err)
	}

	exists, err := di.client.Exists(ctx, buildID, h)
	if err != nil {
		level.Debug(logger).Log("msg", "failed to check whether build ID symbol exists", "err", err)
	}

	if exists {
		di.existsCache.Put(buildID, struct{}{})
		return true
	}

	return false
}
```

**Comment by brancz** [comment]
The build ID does not uniquely identify the file, it uniquely identifies the _build_. This is important because the purpose is for example that one binary that does not have any debuginfos (but the executable `.text` section) has the same build ID as the file that does not contain the `.text` section but the debuginfos, and that way we can link them.

I think in the new upload flow this becomes a bit clearer: https://github.com/parca-dev/parca/pull/2248

**Comment by kakkoyun** [comment]
ref https://github.com/parca-dev/parca-agent/pull/1104

**Comment by kakkoyun** [comment]
> The build ID does not uniquely identify the file, it uniquely identifies the _build_. This is important because the purpose is for example that one binary that does not have any debuginfos (but the executable `.text` section) has the same build ID as the file that does not contain the `.text` section but the debuginfos, and that way we can link them.
> 
> I think in the new upload flow this becomes a bit clearer: [parca-dev/parca#2248](https://github.com/parca-dev/parca/pull/2248)

@zdyj3170101136 Does this answer your question?
