### ISSUE TITLE
parca-agent slowly leaks fds 

### ISSUE THREAD

**Issue by gpl** [parca-dev/parca-agent#1516]
We've noticed that parca-agent v0.9.1 seems to leak ~10-50k fds per day and never closes them.

This eventually locks up the host itself and breaks our systems.

System version: Linux 5.15.99 #1-NixOS SMP Fri Mar 10 08:40:15 UTC 2023 x86_64 GNU/Linux
Runtime: containerd 1.7
Kubernetes: 1.26.3

**Comment by javierhonduco** [comment]
Hi!

The version you are running, `v0.9.1` was released in July 2022 and it's no longer supported. We've made many changes since then, including a file descriptor leak IIRC. We monitor the opened file descriptors in our Demo and production environments and haven't spotted any leaks.

Can you please try the latest version, [`v0.16.0`](https://github.com/parca-dev/parca-agent/releases/tag/v0.16.0) and let us know how it goes?

Thanks!

**Comment by gpl** [comment]
Ah, the latest version seems to have fixed that issue, I've been monitoring it for the past week and it seems stable.

Thanks!
