### ISSUE TITLE
Allow profiling of arbitrary processes

### ISSUE THREAD

**Issue by guettli** [parca-dev/parca-agent#260]
Up to now you can either use "kubernetes" profiling or "systemd-unit".

For local testing I would like the agent to be more flexible.

I would like agent to attach to a pid (or a list of pids) or all processes with a particular name.

Does this make sense to you?

**Comment by brancz** [comment]
I think this is kind of similar to https://github.com/parca-dev/parca-agent/issues/250, so yes I think this would be quite nice to have. We're still thinking about potentially changing the larger architecture of the parca agent potentially, to instead of creating a profiler per cgroup create a single profiler for the entire host. Not that that would conflict with this idea, but I want to have mentioned it.
