### ISSUE TITLE
parca-agent: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by parca-agent)

### ISSUE THREAD

**Issue by tkcreddy** [parca-dev/parca-agent#328]
While starting up the parca-agent, we are getting this error. this is on Amazon Linux instance.

**Comment by kakkoyun** [comment]
@tkcreddy Thanks for reaching out :+1: 

Could you please describe your setup a little more? I assume you install `parca-agent` directly on Amazon Linux and use systemd to discover cgroups? Or this is a Kubernetes setup that uses Amazon Linux (which is more worrisome because I see that dependency presents in the container image)?

https://github.com/parca-dev/parca-agent/blob/bbafe10412a384b64d252f24fdec90d6e3a1e1e2/Dockerfile#L42-L55

In either case, we'll make sure we update our docs or make sure the dependencies are present (either by linking dependencies statically or having dependencies in the container)

**Comment by SINGH-IOT2020** [comment]
I am also getting the same error message while starting the parca-agent in amazon linux ec2 instance. 
Details  are below 👎 
parca-agent.service - Parca Agent
   Loaded: loaded (/etc/systemd/system/parca-agent.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2022-04-07 14:59:16 UTC; 9s ago
  Process: 1460 ExecStart=/usr/bin/parca-agent --http-address=":7071" --node=systemd-test --systemd-units=parca.service,parca-agent.service --kubernetes=false --store-address=localhost:7070 --insecure (code=exited, status=1/FAILURE)
------------------------------------
To fix the above issue I ran command   -systemctl  enable parca-agent 
Still same error message as above
----------------------------------------
Try to start parca agent manually . Got below error message 👍 

# ./parca-agent
./parca-agent: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./parca-agent)

Please suggest and help to resolve this.

**Comment by kakkoyun** [comment]
@SINGH-IOT2020 Could you try installing certain dependencies and try again? For a Debian based distro they look like below:
https://github.com/parca-dev/parca-agent/blob/bbafe10412a384b64d252f24fdec90d6e3a1e1e2/Dockerfile#L15-L18

**Comment by SINGH-IOT2020** [comment]
Hi, Thanks for response. 
I install the dependency and still getting the same error message :
[root@ip-172-31-30-170 ec2-user]# yum install llvm binutils elfutils
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                      | 3.7 kB  00:00:00
Package binutils-2.29.1-31.amzn2.x86_64 already installed and latest version
Package elfutils-0.176-2.amzn2.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package llvm.x86_64 0:11.1.0-1.amzn2.0.2 will be installed
--> Processing Dependency: llvm-libs(x86-64) = 11.1.0-1.amzn2.0.2 for package: llvm-11.1.0-1.amzn2.0.2.x86_64
--> Processing Dependency: libLLVM-11.so(LLVM_11)(64bit) for package: llvm-11.1.0-1.amzn2.0.2.x86_64
--> Processing Dependency: libLLVM-11.so()(64bit) for package: llvm-11.1.0-1.amzn2.0.2.x86_64
--> Running transaction check
---> Package llvm-libs.x86_64 0:11.1.0-1.amzn2.0.2 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================
 Package               Arch               Version                         Repository              Size
=======================================================================================================
Installing:
 llvm                  x86_64             11.1.0-1.amzn2.0.2              amzn2-core              12 M
Installing for dependencies:
 llvm-libs             x86_64             11.1.0-1.amzn2.0.2              amzn2-core              22 M

Transaction Summary
=======================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 34 M
Installed size: 119 M
Is this ok [y/d/N]: y
Downloading packages:
(1/2): llvm-libs-11.1.0-1.amzn2.0.2.x86_64.rpm                                  |  22 MB  00:00:00
(2/2): llvm-11.1.0-1.amzn2.0.2.x86_64.rpm                                       |  12 MB  00:00:00
-------------------------------------------------------------------------------------------------------
Total                                                                   55 MB/s |  34 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : llvm-libs-11.1.0-1.amzn2.0.2.x86_64                                                 1/2
  Installing : llvm-11.1.0-1.amzn2.0.2.x86_64                                                      2/2
  Verifying  : llvm-11.1.0-1.amzn2.0.2.x86_64                                                      1/2
  Verifying  : llvm-libs-11.1.0-1.amzn2.0.2.x86_64                                                 2/2

Installed:
  llvm.x86_64 0:11.1.0-1.amzn2.0.2

Dependency Installed:
  llvm-libs.x86_64 0:11.1.0-1.amzn2.0.2
--------------------------------------------------------------------
# systemctl status parca-agent
● parca-agent.service - Parca Agent
   Loaded: loaded (/etc/systemd/system/parca-agent.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2022-04-07 23:02:20 UTC; 2s ago
  Process: 9755 ExecStart=/usr/bin/parca-agent --http-address=":7071" --node=systemd-test --systemd-units=parca.service,parca-agent.service --kubernetes=false --store-address=localhost:7070 --insecure (code=exited, status=1/FAILURE)
 Main PID: 9755 (code=exited, status=1/FAILURE)

Apr 07 23:02:20 ip-172-31-30-170.ec2.internal systemd[1]: parca-agent.service: main process exited...RE
Apr 07 23:02:20 ip-172-31-30-170.ec2.internal systemd[1]: Unit parca-agent.service entered failed ...e.
Apr 07 23:02:20 ip-172-31-30-170.ec2.internal systemd[1]: parca-agent.service failed.
------------------------------------------------------------------------------------------------
 ./parca-agent
./parca-agent: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./parca-agent)

**Comment by kakkoyun** [comment]
@SINGH-IOT2020 Sorry, I thought those dependencies include libc, could you please check if you have a variant of libc installed on the system?

**Comment by kakkoyun** [comment]
In any case, this is not the UX we would want to have for parca-agent, I've created an issue to solve this in the long run https://github.com/parca-dev/parca-agent/issues/332

**Comment by kakkoyun** [comment]
Closed with #351
