### ISSUE TITLE
profiler: Remove unique label values from the metrics

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#356]
`parca_agent_profiler_failed_stack_unwinding_attempts_total{target="{__cgroup_path__=\"/sys/fs/cgroup/perf_event/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod2ef4eceb_afe7_4f19_ab76_1458216087eb.slice/docker-ff7933c90e305fe74a5ebc5ef0e6c2e3dd71250d3e022c7af9714a215977e7ea.scope\", addonmanager_kubernetes_io_mode=\"Reconcile\", container=\"storage-provisioner\", containerid=\"docker://ff7933c90e305fe74a5ebc5ef0e6c2e3dd71250d3e022c7af9714a215977e7ea\", integration_test=\"storage-provisioner\", namespace=\"kube-system\", node=\"parca-agent\", pod=\"storage-provisioner\"}",type="kernel"} 6`

We are using `target.String()` as is it causes unique label values to leak profiler metrics, we need to remove them

cc @Sylfrena

**Comment by palash25** [comment]
i am guessing this issue can be closed now since its mentioned in this PR description https://github.com/parca-dev/parca-agent/pull/663  that it fixes this issue? 

I also couldn't find any metric named  `parca_agent_profiler_failed_stack_unwinding_attempts_total` i am guessing it was replaced with `parca_agent_profiler_map_attempts_total` and there is no usage of `target.String()`.

**Comment by kakkoyun** [comment]
This might be deprecated. I'm closing it.

@palash25 Thanks for the bring it to our notice.
