### ISSUE TITLE
Consider using libbpfgo usptream kallsym parser

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#665]
https://github.com/aquasecurity/libbpfgo/blob/main/helpers/kernel_symbols.go

**Comment by v-thakkar** [comment]
https://github.com/parca-dev/parca-agent/blob/main/pkg/ksym/ksym.go#L75 :D

**Comment by kakkoyun** [comment]
Yes, I'm trying to make them more visible :see_no_evil:

**Comment by brancz** [comment]
It does not seem to me that the libbpfgo one handles address ranges correctly. I distinctly remember that ranges were important and lookups do not work with exact addresses.

Eg. we do the range lookup here:

https://github.com/parca-dev/parca-agent/blob/bf421e065e30bb65cf237e868555b9c9a74e8328/pkg/ksym/ksym.go#L178-L184

And the libbpfgo one does a direct lookup:

https://github.com/aquasecurity/libbpfgo/blob/60eea00d2f3626bce7f0e60219ea8414b0c5494b/helpers/kernel_symbols.go#L113

Additionally holding all the kernel symbols in memory was a huge memory hog, which is why we resorted to caching the observed ones only.

**Comment by kakkoyun** [comment]
Then it might be a good idea to contribute back upstream with our better version.

**Comment by brancz** [comment]
We can propose it, but I suspect there’s a bit of a trade off at play. We traded off memory for spending more cpu. It depends a lot on how it’s being used, how often it’s used, etc.

**Comment by javierhonduco** [comment]
I just wanted to update this issue as we have changed our kernel symbolizer in https://github.com/parca-dev/parca-agent/pull/708. 

The new implementation loads all the addresses and symbol names in memory, but there are some differences compared to libbpfgo's. Our implementation:
- [Makes fewer allocations](https://github.com/parca-dev/parca-agent/pull/708/files#diff-b7c7825d5918a11047c473ef76472f7b61dffcfb8d21c39b13c9a469c99b8c53R180);
- [Filters out symbols that aren't functions](https://github.com/parca-dev/parca-agent/pull/708/files#diff-b7c7825d5918a11047c473ef76472f7b61dffcfb8d21c39b13c9a469c99b8c53R197-R210);
- [Doesn't store as much information](https://github.com/parca-dev/parca-agent/pull/708/files#diff-b7c7825d5918a11047c473ef76472f7b61dffcfb8d21c39b13c9a469c99b8c53R70), making the data more compact;

Perhaps we could close this issue, and perhaps in the future, contribute our symbolizer to libbpfgo?

**Comment by kakkoyun** [comment]
> Perhaps we could close this issue, and perhaps in the future, contribute our symbolizer to libbpfgo?

I totally agree, let's close this one. And we can contribute back the improvements to the upstream libbpfgo.
