### ISSUE TITLE
wrong object file path

### ISSUE THREAD

**Issue by zdyj3170101136** [parca-dev/parca-agent#781]
in parca-agent,using mmap file to get object file :

```
	filePath := path.Join("/proc", strconv.FormatInt(int64(pid), 10), "/root", m.File)
```
m is profile.mapping.

and in my linux machine, the maps output is:
```
[root@plat-sh-infra-testing-common-jaeger-collector001 18854]# pwd
/proc/18854
[root@plat-sh-infra-testing-common-jaeger-collector001 18854]# cat maps
00400000-00c15000 r-xp 00000000 fd:01 794160                             /usr/local/bin/jaeger-agent
00c15000-0161e000 r--p 00815000 fd:01 794160                             /usr/local/bin/jaeger-agent
0161e000-0166d000 rw-p 0121e000 fd:01 794160                             /usr/local/bin/jaeger-agent
```

the m.file is absolute path.

so i think you should use os.Open(m.file) to get object file.

**Comment by javierhonduco** [comment]
Hi!

This path should be correct due to how [mount namespaces](https://man7.org/linux/man-pages/man7/mount_namespaces.7.html) work. When a process has a different mount namespace than the root one, we have to access the files in `/proc/<pid>/root/<path>`. Although it is not strictly necessary, this also works in case of the mount namespace being the same one as the root

Feel free to reopen this issue if there's something that doesn't look right! :)
